#!/usr/bin/env python3
"""Emit the existing SQLite hub as Postgres INSERTs for the Supabase schema.

The live database is one user, 5 workouts, 5 installs and 54 completions, so a
generated .sql file is a saner migration than any tooling. Fingerprints are left
out on purpose: the trigger recomputes them on insert.

Usage:
    python3 export_sqlite.py <auth-user-uuid> > seed.sql

The uuid is the Supabase Auth user that should own the imported rows — create
the account first, then read its id from the dashboard.
"""

import json
import sqlite3
import sys
import uuid

DB = "/home/toby/.openclaw/workspace/websiteBuilder/backend/workout_hub.db"


def quote(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    owner = sys.argv[1]
    try:
        uuid.UUID(owner)
    except ValueError:
        print(f"'{owner}' is not a uuid", file=sys.stderr)
        return 2

    connection = sqlite3.connect(DB)
    connection.row_factory = sqlite3.Row

    # Old TEXT ids map to new uuids; installs and completions follow the map.
    workout_ids = {}

    print("-- Generated by export_sqlite.py. Review before running.")
    print("begin;")

    for row in connection.execute("SELECT * FROM workouts WHERE visibility = 'public'"):
        new_id = str(uuid.uuid4())
        workout_ids[row["id"]] = new_id
        print(
            "insert into public.workouts "
            "(id, owner_user_id, name, description, exercises, weight_unit, visibility, created_at) "
            f"values ({quote(new_id)}, {quote(owner)}, {quote(row['name'])}, "
            f"{quote(row['description'])}, {quote(row['exercises_json'])}::jsonb, "
            f"{row['weight_unit']}, 'public', {quote(row['created_at'])});"
        )

    for row in connection.execute("SELECT * FROM workout_installs"):
        target = workout_ids.get(row["workout_id"])
        if target is None:
            continue
        print(
            "insert into public.workout_installs "
            "(user_id, workout_id, provider_template_id, provider_template_code, status, installed_at) "
            f"values ({quote(owner)}, {quote(target)}, {quote(row['provider_template_id'])}, "
            f"{quote(row['provider_template_code'])}, {quote(row['status'])}, "
            f"{quote(row['installed_at'])}) on conflict (user_id, workout_id) do nothing;"
        )

    for row in connection.execute("SELECT * FROM completions"):
        target = workout_ids.get(row["workout_id"])
        if target is None:
            continue
        summary = row["provider_summary_json"] or "{}"
        json.loads(summary)  # fail loudly here rather than inside Postgres
        print(
            "insert into public.completions "
            "(user_id, workout_id, provider_record_id, completed_at, total_volume_lbs, "
            "duration_seconds, verified, provider_summary, created_at) "
            f"values ({quote(owner)}, {quote(target)}, {quote(row['provider_record_id'])}, "
            f"{quote(row['completed_at'])}, {row['total_volume_lbs']}, {row['duration_seconds']}, "
            f"{'true' if row['verified'] else 'false'}, {quote(summary)}::jsonb, "
            f"{quote(row['created_at'])}) on conflict (user_id, provider_record_id) do nothing;"
        )

    print("commit;")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
